In [2]:
import pandas as pd
import numpy as np

data_dump = pd.read_excel('BookingReport.xlsx')
print(data_dump)

          LAKELAND CARGO LOGISTICS Ltd     Unnamed: 1 Unnamed: 2  \
0                       Booking Report            NaN        NaN
1     Date: 02-Jul-2021 To 02-Jul-2021            NaN        NaN
2                      BranchName: All            NaN        NaN
3            Destination City: --All--            NaN        NaN
4                              Summary            NaN        NaN
...                                ...            ...        ...
1182                              1167  HO_4469\14746     Nakuru
1183                              1168  HO_4469\14747     Nakuru
1184                              1169  HO_4469\14748     Nakuru
1185                              1170  HO_4469\14749     Nakuru
1186                             Total            NaN        NaN

           Unnamed: 3          Unnamed: 4      Unnamed: 5  \
0                 NaN                 NaN             NaN
1                 NaN                 NaN             NaN
2                 NaN                 NaN             NaN
3                 NaN                 NaN             NaN
4                 NaN                 NaN             NaN
...               ...                 ...             ...
1182  NAKURU LAKELAND  02-Jul-21 10:08 PM   Belvin Andeka
1183  NAKURU LAKELAND  02-Jul-21 10:09 PM  Shynancy Netia
1184  NAKURU LAKELAND  02-Jul-21 10:09 PM   Belvin Andeka
1185  NAKURU LAKELAND  02-Jul-21 10:10 PM  Shynancy Netia
1186              NaN                 NaN             NaN

                           Unnamed: 6        Unnamed: 7     Unnamed: 8  \
0                                 NaN               NaN            NaN
1                                 NaN               NaN            NaN
2                                 NaN               NaN            NaN
3                                 NaN               NaN            NaN
4                                 NaN               NaN            NaN
...                               ...               ...            ...
1182  HO_LAKELAND CARGO LOGISTICS Ltd  GREENHILL CABLES     KAGI ELECT
1183  HO_LAKELAND CARGO LOGISTICS Ltd        cooper ltd         shalis
1184  HO_LAKELAND CARGO LOGISTICS Ltd     KINGSWAY TYRE  KINGSWAY TYRE
1185  HO_LAKELAND CARGO LOGISTICS Ltd            mudoba          henry
1186                              NaN               NaN            NaN

     Unnamed: 9 Unnamed: 10 Unnamed: 11                       Unnamed: 12  \
0           NaN         NaN         NaN                               NaN
1           NaN         NaN         NaN  Print Date: 02-Jul-2021 10:31 PM
2           NaN         NaN         NaN                     Is Refund: No
3           NaN         NaN         NaN                 Payment Type: All
4           NaN         NaN         NaN                               NaN
...         ...         ...         ...                               ...
1182       Sack           1        2100                         ONACCOUNT
1183       Sack           2         600                              PAID
1184      Cover           1         200                         ONACCOUNT
1185    Package           1         200                              PAID
1186        NaN        1902      676954                               NaN

     Unnamed: 13 Unnamed: 14
0            NaN         NaN
1            NaN         NaN
2            NaN         NaN
3            NaN         NaN
4            NaN         NaN
...          ...         ...
1182      BOOKED         NaN
1183      BOOKED   pd..edwin
1184      BOOKED         NaN
1185      BOOKED  pd..mathew
1186         NaN         NaN

[1187 rows x 15 columns]

In [3]:
data_dump = data_dump.drop(labels=range(0,15),axis=0)
data_dump = data_dumpdf. columns=iloc[0]
print(data_dump)

     LAKELAND CARGO LOGISTICS Ltd     Unnamed: 1        Unnamed: 2  \
15                            SR.         WB No.  Destination City
16                              1     LLKRN\5078           Kericho
17                              2     LLKRN\5079           Mombasa
18                              3     LLKRN\5080            Kitale
19                              4     LLKRN\5081           Mombasa
...                           ...            ...               ...
1182                         1167  HO_4469\14746            Nakuru
1183                         1168  HO_4469\14747            Nakuru
1184                         1169  HO_4469\14748            Nakuru
1185                         1170  HO_4469\14749            Nakuru
1186                        Total            NaN               NaN

              Unnamed: 3          Unnamed: 4           Unnamed: 5  \
15    Destination Branch    Booking DateTime       Booked By User
16      KERICHO LAKELAND  02-Jul-21 09:59 AM  BENARD OWINO OPONDO
17      MOMBASA LAKELAND  02-Jul-21 10:23 AM  BENARD OWINO OPONDO
18       KITALE LAKELAND  02-Jul-21 10:47 AM  BENARD OWINO OPONDO
19      MOMBASA LAKELAND  02-Jul-21 10:49 AM  BENARD OWINO OPONDO
...                  ...                 ...                  ...
1182     NAKURU LAKELAND  02-Jul-21 10:08 PM        Belvin Andeka
1183     NAKURU LAKELAND  02-Jul-21 10:09 PM       Shynancy Netia
1184     NAKURU LAKELAND  02-Jul-21 10:09 PM        Belvin Andeka
1185     NAKURU LAKELAND  02-Jul-21 10:10 PM       Shynancy Netia
1186                 NaN                 NaN                  NaN

                           Unnamed: 6         Unnamed: 7  \
15                   Booked By Branch        Sender Name
16              KIRINYAGA RD LAKELAND  Al Qaayam Trading
17              KIRINYAGA RD LAKELAND              Ahmed
18              KIRINYAGA RD LAKELAND        Peter maina
19              KIRINYAGA RD LAKELAND      Daniel Sikoyo
...                               ...                ...
1182  HO_LAKELAND CARGO LOGISTICS Ltd   GREENHILL CABLES
1183  HO_LAKELAND CARGO LOGISTICS Ltd         cooper ltd
1184  HO_LAKELAND CARGO LOGISTICS Ltd      KINGSWAY TYRE
1185  HO_LAKELAND CARGO LOGISTICS Ltd             mudoba
1186                              NaN                NaN

                             Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
15                        Receiver Name       Item       Units     Freight
16                     Flex Auto Spares        Box           1         400
17                      A&A Company ltd       Sack           1         300
18                   Skulab Enterprises        Box           1         250
19    Cyprian Okuku (Carmex Automobile)    Package           1         250
...                                 ...        ...         ...         ...
1182                         KAGI ELECT       Sack           1        2100
1183                             shalis       Sack           2         600
1184                      KINGSWAY TYRE      Cover           1         200
1185                              henry    Package           1         200
1186                                NaN        NaN        1902      676954

       Unnamed: 12      Unnamed: 13 Unnamed: 14
15    Payment Type           Status       Desc.
16             COD  BRANCH RECEIVED         NaN
17            PAID  BRANCH RECEIVED         NaN
18             COD  BRANCH RECEIVED         NaN
19            PAID  BRANCH RECEIVED         NaN
...            ...              ...         ...
1182     ONACCOUNT           BOOKED         NaN
1183          PAID           BOOKED   pd..edwin
1184     ONACCOUNT           BOOKED         NaN
1185          PAID           BOOKED  pd..mathew
1186           NaN              NaN         NaN

[1172 rows x 15 columns]